install:
	./gradlew installDist

run-dist:
	./build/install/app/bin/app

clean:
	./gradlew clean

build:
	./gradlew build

test:
	./gradlew test

lint-main:
	./gradlew checkstyleMain

lint-test:
	./gradlew checkstyleTest

coverage:
	./gradlew jacocoTestReport

update-check:
	./gradlew dependencyUpdates

.PHONY: build